### ISSUE TITLE
Stacking Apartments vertically along the Z axis

### ISSUE THREAD

**Issue by LucaJeevanjee** [grebtsew/FloorplanToBlender3d#10]
Hi there, great work on the project. I have been working on stacking the floor-plans vertically along the Z axis by increasing the Z value in the transformation by 1 for every inputted floor plan.

Currently, it is working for 10 floors.

However, for some bizarre reason, after the 10th floor, the rest (say the last 10 if I inputted 20), all position themselves at the max Z axis (20 in this case) leaving a large gap where the floors of the 11 to 19 should be.

I'm not entirely sure why this is happening, but wondered if it might be something to do with the transformation code that I am missing.

Thanks again!

**Comment by grebtsew** [comment]
Hello, 

Thanks for checking out the project! 
I did some stacking in X,Y,Z axis in the early implementation, I'm not sure if you are using that implementation or creating your own. There might be several issues with my old implementation. Do you have any requirements? Like for instance, how many floorplans do you eventually want to add? 

This is a good solveable issue, if anyone wants to contribute, this might be a good start.

As usual I have a lot to do, so I can't promise that I will have time to fix this within 2-4 weeks. 
Hope that's fine. I will let you know If I create a solution.

Cheers,
@grebtsew

**Comment by LucaJeevanjee** [comment]
Hi, in your implementation I could see stacking horizontally and vertically however, these were only along the x and y axis, not the z axis. I am hoping to be able to add an unlimited amount of floors, say max 100. 

Currently I have just looped through the inputted `image_paths` variable and have edited the `create` vertically function to change the `z-axis` parameter in the transform parameter passed to the `generate` function to  increase by `1` (the height of each floor) for every floor. Not sure exactly what's going wrong as when I print out the final position when its generating, they are in the correct position, could it possibly be on Blender's side?

I was thinking that it would be cool to create a grid based system to organize and generate floors. So you could put for example: 3 floors horizontally with 50 floors along the Z axis vertically, but this is further off.

**Comment by grebtsew** [comment]
Yes, I created two ways of adding several floorplans. 

One is to add them X, and Y as you mention. The issue can as you mention possibly be in the blender script.

The other one I use the file_structure variable from config.ini to decide where in a 3dim array a floorplan should be placed relative to eachother. I don't think there are any documentation for how to use the functionality though.

**Comment by LucaJeevanjee** [comment]
Hey, yes I saw that but was unsure of what it was. I'll play around with it to see if I can achieve the desired result

**Comment by grebtsew** [comment]
Okey, if I remember correctly it is quite buggy, but hopefully something still works. Good luck!

Generally we use the get_shape(verts, scale) function. The shape (x,y,z) describe the floorplan size in x,y,z. Then we have a position (x,y,z) and rotation (x,y,z) used to place them correcly. I would guess that something is wrong with that calculation either in the main code or in the blender script. 

I am also working on window and door detection on a seperate branch. Where I have done some mayor restructuring of the project, so my plan was to document, test and update the floorplan stacking functionality before merging. 

Currently I have a huge deadline for december 20th, I promise you to help more with this and update the project when I'm done with the deadline.

**Comment by grebtsew** [comment]
Hi again,

I might have found the issue now. 

There are two problems: 

1. If we want to create 25 floorplans. N = 25

One problem seems to be that the blender script then always use the index 0 - 24. So if you have any cached or previously generated data in the ./Data/ folder those will be used instead. 

So a quickfix would be for now to always remove the Data folder before each run.

2. The data folder incrementor puts all floorplans above index 10 in the same folder due a bug in the implementation of the ´create_new_floorplan_path(path)´ function!

If you replace it with this, it should be fine for now
```
def create_new_floorplan_path(path):
    """
    Creates next free name to floorplan data
    @Param path, path to floorplan
    @Return end path
    """
    res = 0
    for _, dirs, _ in os.walk(path):
        for _ in dirs:
            try:
                name_not_found = True
                while name_not_found:
                    if not os.path.exists(path + str(res) + "/"):
                        break
                    res +=1
            except Exception:
                continue
            
    res = path + str(res) + "/"
    if not os.path.exists(res):
        os.makedirs(res)
    return res
```

I'm currently working on a nice fix for these issues, also with generation along axises instead of horizontal and vertical. I am also gonna add solution to reuse generated floorplan-data to speed up stacking, by simply storing more information in the transform files.

Let me know if this quickfix works for now.

See image below, with 20 floorplans.
![bild](https://user-images.githubusercontent.com/8101164/147543200-a8aa64d0-4c66-4de7-ae39-bb2721dd90c0.png)


Cheers,
@grebtsew

**Comment by LucaJeevanjee** [comment]
Hey, I agree generation along axis is a more optimal solution. I've been playing around with a grid based system but to no avail yet!

By the way, how did you get the windows and doors working?

**Comment by LucaJeevanjee** [comment]
So just tested the fixes out and they are working better 👍🏼

**Comment by grebtsew** [comment]
Great! I'm currently working on the doors-and-windows branch.

It contains a bunch of new features that will be released/merged with main, as soon as I'm done with my list of tasks. 
I'm gonna remove the grid/matrix stacking and replace it with a naive recipe file parsing system instead. See example here: https://github.com/grebtsew/FloorplanToBlender3d/blob/doors-and-windows/Stacking/example.txt
I will make sure to document it better also. It feels more user friendly and costumizable.

**Comment by grebtsew** [comment]
Hi!

Today I updated the main/master branch with a new stacking system. It should solve this issue for now.

Cheers,
@grebtsew

**Comment by LucaJeevanjee** [comment]
> Hi!
> 
> Today I updated the main/master branch with a new stacking system. It should solve this issue for now.
> 
> Cheers,
> @grebtsew

Awesome!
