### ISSUE TITLE
Detecting Windows and Doors

### ISSUE THREAD

**Issue by frankkim1108** [grebtsew/FloorplanToBlender3d#23]
Hi @grebtsew !!

I am trying out your code for creating a 3D house model with 2D floorplan image.
I have successfully create a blender 3D model that only shows walls and the floor.
After that I tried to add doors and windows to the 3D model.
However, the code that you wrote using opencv orb to match features between the door model and the floorplan image only worked well on the first example floorplan image.
I tried to detect windows and doors with other floorplans but the accuracy seems to quite low. 

![image](https://user-images.githubusercontent.com/43432293/184125638-7ad59bba-ae7c-4b32-87df-9fbaf13c7cbe.png)

Would there be a way to improve the accuracy or part of the code that I could mess around the values to make it work well on other floorplans?

Thank you for you time and I'm having a great time testing out your code.

**Comment by grebtsew** [comment]
Hello @frankkim1108,

Thanks for testing the implementation!

Yes, the current windows and doors detection is mainly a test implementation. 
Unfortunately, I do not have any plans to reimplement the solution in the near future.

If you however want to improve your results I do have a couple of suggestions.

1. Change the door template image. The doors are detected using template matching, meaning that we are looking for a specific door in the entire floorplan. If the door style of your floorplan is different, then I would recommend to replace the door template image with a new image of a door from your floorplan. Checkout the variable `DOOR_MODEL = "Images/Models/Doors/door.png"`. My plan was to in the future use a folder containing common door formats that could be evaluated for best result.

2. Try changing constants in `const.py`. If I remember correctly there are a couple of constant variables that will change the result of the window and door detection. Some examples : `DETAILS_GAP_IN_WALL_THRESHOLD`, `WINDOWS_RESCALE_TO_FIT`, `DOOR_ANGLE_HIT_STEP` , `WINDOWS_AND_DOORS_FEATURE_N`, `WINDOWS_AND_DOORS_FEATURE_TRACK_QUALITY` and so on. I do not remember exactly what all variables do.

I hope these suggestions help. 

Cheers,
@grebtsew

**Comment by frankkim1108** [comment]
Hi @grebtsew !

Thank you for your time to respond to my question.
I'll try out the suggestions you've given to me.
