### ISSUE TITLE
How to add the top of walls

### ISSUE THREAD

**Issue by dogfootruler-kr** [grebtsew/FloorplanToBlender3d#6]
Hello sir and many thanks for your amazing job on the project!

Is there a possibility to add the top of walls?

As you can see on this screenshot, my walls are hollowed and I would like to add the "roof" above the walls.
![image](https://user-images.githubusercontent.com/3510343/127412934-178b559e-35bf-4830-9b60-36d0d80b34b4.png)

Is it possible and if so how should I do it?

Best regards!

**Comment by dogfootruler-kr** [comment]
So I made it work yesterday by adding top wall verts and faces in the generate.py file
```
    # Create top walls verts
    wall_count = 0
    verts = []
    for box in boxes:
        verts.extend([transform.scale_point_to_vector(box, scale, 0)])
        wall_count += 1

    # create faces
    faces = []
    for room in verts:
        count = 0
        temp = ()
        for _ in room:
            temp = temp + (count,)
            count += 1
        faces.append([(temp)])

    # One solution to get data to blender is to write and read from file.
    IO.save_to_file(path+"top_wall_verts", verts, info)
    IO.save_to_file(path+"top_wall_faces", faces, info)
```

and adding the mesh in the blender script like this:

```
    '''
    Create Top  Walls
    '''
    # get image top wall data
    verts = read_from_file(path_to_top_wall_verts_file)
    faces = read_from_file(path_to_top_wall_faces_file)

    # Create mesh from data
    boxcount = 0
    wallcount = 0

    # Create parent
    top_wall_parent, top_wall_parent_mesh = init_object("TopWalls")

    for i in range(0, len(verts)):
        roomname = "TopWalls"+str(i)
        obj = create_custom_mesh(
            roomname, verts[i], faces[i], pos=pos, rot=rot, cen=cen, mat=create_mat((0.5, 0.5, 0.5, 1)))
        obj.parent = top_wall_parent

    top_wall_parent.parent = parent
```

Are you interested in a PR maybe?

**Comment by grebtsew** [comment]
Hello @dogfootruler-kr,

It's nice to hear that you like the project. 

You seem to have created a good solution too. I can absolutely take a look at a PR!

Cheers,
@grebtsew

**Comment by grebtsew** [comment]
Code as been merged, thanks for the contribution!

I will now close this issue.
